Repository WOK-AT/WOKAT-SERVER, pull requests merged in 2023-05, with the labels that each got.

#10 [Feature] S3 이미지 업로드 기능 추가
  .github/workflows/docker.yml
  build.gradle
  src/main/java/com/sopt/wokat/global/config/AmazonS3Config.java
  src/main/java/com/sopt/wokat/infra/aws/S3ProfileImageUploader.java
  src/main/resources/application.yml
  src/test/java/com/sopt/wokat/aws/s3/ImageUploadTest.java
  temp.png
Labels: ✨ Feature, 다현

#12 [Feature] 유저 프로필 이미지 S3 저장
  .gitignore
  dump.rdb
  src/main/java/com/sopt/wokat/domain/member/controller/OauthController.java
  src/main/java/com/sopt/wokat/domain/member/dto/OauthResponse.java
  src/main/java/com/sopt/wokat/domain/member/dto/ProfileImageUploadDTO.java
  src/main/java/com/sopt/wokat/domain/member/entity/Member.java
  src/main/java/com/sopt/wokat/domain/member/entity/MemberProfile.java
  src/main/java/com/sopt/wokat/domain/member/entity/ProfileImage.java
  src/main/java/com/sopt/wokat/domain/member/oauth/OauthAttributes.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepository.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/member/service/KakaoOauthResponse.java
  src/main/java/com/sopt/wokat/domain/member/service/MemberService.java
  src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
  src/main/java/com/sopt/wokat/infra/aws/DownlaodFileS3Uploader.java
  src/main/java/com/sopt/wokat/infra/aws/S3ProfileImageUploader.java
  src/test/java/com/sopt/wokat/DB/MemberTest.java
  src/test/java/com/sopt/wokat/aws/s3/ImageUploadTest.java
  temp.png
Labels: ✨ Feature, ✅ Test, 다현

#13 [Feature] 공간 엔티티 작성
  src/main/java/com/sopt/wokat/domain/member/controller/MemberController.java
  src/main/java/com/sopt/wokat/domain/member/controller/OauthController.java
  src/main/java/com/sopt/wokat/domain/member/dto/MemberResponse.java
  src/main/java/com/sopt/wokat/domain/place/entity/.gitkeep
  src/main/java/com/sopt/wokat/domain/place/entity/Space.java
  src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
  src/main/java/com/sopt/wokat/global/config/SwaggerConfig.java
Labels: ✨ Feature, 다현

#15 [Fix] Member 엔티티 변경 및 관련 로직 수정
  src/main/java/com/sopt/wokat/domain/member/dto/OauthResponse.java
  src/main/java/com/sopt/wokat/domain/member/entity/Member.java
  src/main/java/com/sopt/wokat/domain/member/entity/MemberProfile.java
  src/main/java/com/sopt/wokat/domain/member/entity/ProfileImage.java
  src/main/java/com/sopt/wokat/domain/member/entity/UploadFile.java
  src/main/java/com/sopt/wokat/domain/member/oauth/OauthAttributes.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepository.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/member/service/MemberService.java
  src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
  src/main/java/com/sopt/wokat/global/entity/BaseEntity.java
  src/test/java/com/sopt/wokat/DB/MemberTest.java
Labels: 🐞 BugFix, 다현

#16 [Feature] 공간 Post
  src/main/java/com/sopt/wokat/domain/member/entity/Member.java
  src/main/java/com/sopt/wokat/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/member/service/KakaoOauthResponse.java
  src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
  src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
  src/main/java/com/sopt/wokat/domain/place/dto/.gitkeep
  src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
  src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceRequest.java
  src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceResponse.java
  src/main/java/com/sopt/wokat/domain/place/entity/Space.java
  src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
  src/main/java/com/sopt/wokat/domain/place/exception/.gitkeep
  src/main/java/com/sopt/wokat/domain/place/exception/FileUploadException.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepository.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
  src/main/java/com/sopt/wokat/global/config/SwaggerConfig.java
  src/main/java/com/sopt/wokat/global/config/security/WebSecurityConfig.java
  src/main/java/com/sopt/wokat/global/error/ErrorCode.java
  src/main/java/com/sopt/wokat/global/result/ResultCode.java
  src/main/java/com/sopt/wokat/global/util/SecurityUtil.java
  src/main/java/com/sopt/wokat/infra/aws/S3PlaceUploader.java
  src/main/java/com/sopt/wokat/infra/aws/S3ProfileUploader.java
  src/main/resources/application.yml
  src/test/java/com/sopt/wokat/aws/s3/ImageUploadTest.java
Labels: ✨ Feature, 📬 API, 다현

#17 [Feature] 도로명주소 <-> 지번주소 변환 GET
  build.gradle
  src/main/java/com/sopt/wokat/domain/member/exception/oauth/OauthAttributes.java
  src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
  src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
  src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepository.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
  src/main/java/com/sopt/wokat/global/config/security/WebSecurityConfig.java
  src/test/java/com/sopt/wokat/DB/PlaceTest.java
Labels: ✨ Feature, 📬 API, 예린

#18 [Feature] 특정 장소 조회
  src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
  src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
  src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
  src/main/java/com/sopt/wokat/domain/place/exception/PlaceNotFoundException.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
  src/main/java/com/sopt/wokat/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sopt/wokat/global/error/ErrorCode.java
  src/main/java/com/sopt/wokat/global/result/ResultCode.java
  src/test/java/com/sopt/wokat/DB/RedisTest.java
  src/test/java/com/sopt/wokat/aws/s3/ImageUploadTest.java
Labels: ✨ Feature, 📬 API, 다현

#22 [Fix] uri 변경 및 리턴 값 변경
  src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
  src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
Labels: 📬 API, 🔨 Refactor, 다현
